### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gabrielschulhof** [asciidisco/grunt-qunit-istanbul#45]
Hi!

Can we please have a new release which includes Jörn's updated bridge? We kinda need it for jQuery Mobile.

TIA!

**Comment by asciidisco** [comment]
Sure.
Are there any other dependencies that need to be updated or anything that needs to be changed?
//cc @jzaefferer

**Comment by jzaefferer** [comment]
Looks like you just need to tag and publish https://github.com/asciidisco/grunt-qunit-istanbul/commit/e152e39a7a30097af10048604a55b5e2741154cb

**Comment by gabrielschulhof** [comment]
Bump!

**Comment by asciidisco** [comment]
Sorry, I just moved houses & I do not have a working internet connection yet, as well as only a 2G connection via mobile at home...
Visiting some friends on Sunday & will hijack their connection to package everything up.

Sorry for the delay & a big thank you for helping out :)
//cc @jzaefferer @gabrielschulhof

**Comment by gabrielschulhof** [comment]
NP! Don't over-exert yourself, @asciidisco :)

**Comment by asciidisco** [comment]
Finally, merged & released as 0.6.0
